apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
        app: workshop
type: Opaque
data:
  MYSQL_USER: Y2Fycw==
  MYSQL_PASSWORD: Y2FyczEyMw==
  MYSQL_DATABASE: Y2Fycw==
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: workshop
    component: mysql
    type: infra
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: workshop
        component: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        image: mysql
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: workshop
    component: mysql
    type: infra
spec:
  type: NodePort
  selector:
    app: workshop
    component: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: workshop
    component: eureka
    type: infra
  name: eureka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: workshop
        component: eureka
        type: infra
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8080"
        image: marcopaga/docker-workshop-eureka
        name: eureka
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
    component: eureka
    type: infra
  name: eureka
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: workshop
    component: eureka
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: workshop
    component: cars
    type: service
  name: cars
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workshop
        component: cars
        type: service
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka:8080/eureka"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/cars"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_ZIPKIN_BASEURL
          value: http://zipkin:9411
        image: marcopaga/docker-workshop-cars
        name: cars
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
    component: cars
    type: service
  name: cars
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: workshop
    component: cars
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: workshop
    component: locations
    type: service
  name: locations
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: workshop
        component: locations
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka:8080/eureka"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_ZIPKIN_BASEURL
          value: http://zipkin:9411
        image:  marcopaga/docker-workshop-locations
        name: locations
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
    component: locations
    type: service
  name: locations
spec:
  type: NodePort
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  selector:
    app: workshop
    component: locations
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: workshop
    component: maintenance
    type: service
  name: maintenance
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: workshop
        component: maintenance
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka:8080/eureka"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_ZIPKIN_BASEURL
          value: http://zipkin:9411
        image: marcopaga/docker-workshop-maintenance
        name: maintenance
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workshop
    component: maintenance
    type: service
  name: maintenance
spec:
  type: NodePort
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8080
  selector:
    app: workshop
    component: maintenance
status:
  loadBalancer: {}