version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  frontend:
    build: frontend/.
    image: marcopaga/plain-frontend:1
    ports:
      - "8091:8091"
    environment:
      - ZIPKIN_HOST=zipkin
    depends_on:
      - zipkin
  backend:
    build: backend/.
    image: marcopaga/plain-backend:1
    ports:
      - "8090:8090"
    environment:
      - ZIPKIN_HOST=zipkin
    depends_on:
      - zipkin
