version: '3'

services:
  frontend:
    build: frontend/.
    image: marcopaga/plain-frontend:1
    ports:
      - "8091:8091"
      - "8080:8091"
    depends_on:
      - backend
  backend:
    build: backend/.
    image: marcopaga/plain-backend:1
    ports:
      - "8090:8090"
