server:
  port: 8090

management:
  security:
    enabled: false

backend:
  processing:
    time:
      max: 1100

spring:
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/